# Generated by Django 5.2.6 on 2025-10-25 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='checkout',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
