# Generated by Django 5.2.6 on 2025-10-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='is_mpv',
            new_name='is_mvp',
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='00000000', max_length=20),
        ),
    ]
