# Generated by Django 5.2.6 on 2025-10-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('category', models.TextField(blank=True)),
                ('city', models.CharField(choices=[('Cebu', 'Cebu'), ('Bali', 'Bali'), ('Bangkok', 'Bangkok'), ('Hawaii', 'Hawaii'), ('Singapore', 'Singapore'), ('Tokyo', 'Tokyo')], max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
