# Generated by Django 5.2.6 on 2025-10-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_listing',
            name='category',
            field=models.TextField(choices=[('Food and Beverage', 'Food and Beverage'), ('Administratvie', 'Administratvie'), ('Intern', 'Intern'), ('Stewarding', 'Stewarding'), ('Outlets', 'Outlets')], max_length=50),
        ),
    ]
