# Generated by Django 5.2.6 on 2025-10-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('Cebu', 'Cebu'), ('Bali', 'Bali'), ('Bangkok', 'Bangkok'), ('Hawaii', 'Hawaii'), ('Singapore', 'Singapore'), ('Tokyo', 'Tokyo')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('rooms', models.IntegerField()),
                ('restaurants', models.IntegerField()),
                ('facilities', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-list_date',),
                'indexes': [models.Index(fields=['list_date'], name='hotel_listi_list_da_baa10e_idx')],
            },
        ),
    ]
