# Generated by Django 5.2.6 on 2025-10-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_listing',
            name='email',
            field=models.EmailField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='hotel_listing',
            name='phone',
            field=models.CharField(default='00000000', max_length=20),
        ),
    ]
