# Generated by Django 5.2.6 on 2025-10-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_listings', '0002_hotel_listing_email_hotel_listing_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_listing',
            name='discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel_listing',
            name='is_onsale',
            field=models.BooleanField(default=True),
        ),
    ]
