# Generated by Django 5.2.6 on 2025-10-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_listings', '0003_hotel_listing_discount_hotel_listing_is_onsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_listing',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
