# Generated by Django 5.2.6 on 2025-10-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_listings', '0004_alter_hotel_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_listing',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
