# Generated by Django 5.2.6 on 2025-10-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_listings', '0005_alter_hotel_listing_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_listing',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
